config/routes.rb
Rails.application.routes.draw do
  #get 'static_pages/top'
  root 'static_pages#top'
  #get '/tweets', to:'tweets#new'
  # link_to にしか使えない
  get '/tweets', to: 'tweets#new', as: 'new_tweet'
  post '/tweets/create', to: 'tweets#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
require 'csv'
class StaticPagesController < ApplicationController
  def top
    #csv = CSV.read('tmp/tweets.csv')
    #@tweets = csv
    @tweets = Tweet.all # all はデータアクセスメソッドと呼ぶ
  end
end

app/controllers/tweets_controller.rb
require "csv"
class TweetsController < ApplicationController
    def new
        @errors = []
    end
    
    # 新規処理のアクション
    def create
        @errors = []
        if params[:name].empty?
            @errors << 'ユーザ名が未入力です'
        end
        if params[:tweet].empty?
            @errors << 'つぶやき内容が未入力です'
        end
        if params[:tweet].length > 140
            @errors << 'つぶやきは140文字以内で入力してください'
        end
        
        # new は view の名前。and return は　以後の処理を終了するおまじない
        if @errors.present?
            render 'new' and return
        end
        
        @tweet = Tweet.new(name: params[:name], tweet: params[:tweet])
        if @tweet.save
            redirect_to(root_path)
        else
            render 'new' and return
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bbs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "ひことこ掲示板", root_path %></h1>
      <ul>
          <li>
              <%= link_to "新規投稿", new_tweet_path %>
          </li>
      </ul>
    </header>
    <%= yield %>
  </body>
</html>

app/views/static_pages/top.html.erb
<div class="top">
    <h2>いまどうしてるの？をつぶやこう</h2>
    <div class="tweets">
        <ul>
            <% @tweets.each do |tweet| %>
            <li>
                <%= tweet.name %>：<%= tweet.tweet %>
                <span><%= tweet.created_at.strftime('%Y/%m/%d %H:%M:%S') %></span>
            </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="new-tweet">
    <div class="errors">
        <% @errors.each do |error| %>
            <p><%= error %></p>
        <% end%>
    </div>
    <!-- <form method="post"> -->
    <%= form_tag("/tweets/create") do %>    
        <div class="text-wrap">
            <input type="text" name="name" placeholder="ユーザ名" value="<%= params[:name] %>">
        </div>
        <div class="textarea-wrap">
            <textarea name="tweet" placeholder="つぶやきを140字以内で記述"><%= params[:tweet] %></textarea>
        </div>
        <input type="submit" value="送信">
    <% end %>
    <!-- </form> -->
</div>